### ISSUE TITLE
Object created by factory, leads to no type-hinting.

### ISSUE THREAD

**Issue by Danack** [pbyrne84/DynamicReturnTypePlugin#16]
I have the same 'maker' object, that is either created directly or by a factory object. When it is created directly the return type hinting works. When it is created by the factory, then it doesn't work

i.e. this works:

```
$maker = new Maker();
$object = $maker->make('foo');
$object->foo(); 
```

This doesn't work:

```
$makerFactory = new MakerFactory();
$maker = $makerFactory->create();
$object = $maker->make('foo');

$object->foo(); //Method 'foo' not found in class.
```

The '$maker' object has the same type hinting in both cases, 

Example files are [here](https://gist.github.com/Danack/8123572)

cheers
Dan

**Comment by pbyrne84** [comment]
I have completely reworked all this to enable fluent chaining in these cases as is was a bit hacky/built on false presumption.
