### ISSUE TITLE
Array Access?

### ISSUE THREAD

**Issue by christianmagill** [pbyrne84/DynamicReturnTypePlugin#23]
Any possibility of seeing support for array access? 

For example in an instance of "Silex\Application"

$app['twig']->

Would recognize the key as an instance of "Twig_Environment"

**Comment by pbyrne84** [comment]
The good news is array access has been added to the api so I can fix this issue.

https://youtrack.jetbrains.com/issue/WI-17116

**Comment by christianmagill** [comment]
Awesome!

**Comment by pbyrne84** [comment]
Okay these examples are covered in the 9 branch
https://github.com/pbyrne84/DynamicReturnTypePluginTestEnvironment/blob/master/TestEnvironment/lib/DynamicReturnTypePluginTestEnvironment/ArrayAccessTest.php#L18-18

**Comment by pbyrne84** [comment]
I assume I can close
