### ISSUE TITLE
Honor types declared in included files

### ISSUE THREAD

**Issue by rakeev** [pbyrne84/DynamicReturnTypePlugin#28]
If factory object created and used in the same file, all works as expected.
![dyn1](https://cloud.githubusercontent.com/assets/1861570/3198966/7098c692-ed61-11e3-9fdd-9aeac44980a9.png)
But if we include that file from another one, dynamic type hinting (for "prepare" in this case) does not work. PHPstorm correctly determines that $di is instance of Dice class, nevertheless plugin does not use this info.
![dyn2](https://cloud.githubusercontent.com/assets/1861570/3198967/750942ec-ed61-11e3-8a3f-0ad4c5fa2a64.png)

If I add phpdoc /** @var Jasrags\Dice $di */ all works. But adding this to every page is a pain. Please don't shame me - it is legacy 10yr old page-controller project =)

Could you make plugin to use types from included files, if it is not so difficult to implement. That would be great.

**Comment by pbyrne84** [comment]
I have looked into this and it is should be achievable. I thought PHPStorm did not analyze the includes but I can ask the index what type the variable is which is what I need to know. I'll have a play with it tomorrow.

**Comment by pbyrne84** [comment]
I have implemented this as described by
https://github.com/pbyrne84/DynamicReturnTypePluginTestEnvironment/blob/master/lib/DynamicReturnTypePluginTestEnvironment/DeclarationIncFile.php

https://github.com/pbyrne84/DynamicReturnTypePluginTestEnvironment/blob/master/lib/DynamicReturnTypePluginTestEnvironment/InclusionFile.php

If you are still interested as it has been a while and it doesn't work as intended in some way let me know and I will add edge cases to these files so I can fix it and not suffer regressions.

Thanks

**Comment by rakeev** [comment]
Yeah, it works perfectly! Thanks a lot.
