### ISSUE TITLE
Class Name in variable

### ISSUE THREAD

**Issue by alecsammon** [pbyrne84/DynamicReturnTypePlugin#37]
Hi - fantastic plugin - thank you

I'm having issues if the parameter is a variable, not a string - as in the following example

```
$className = '\DomDocument';
$dd = mock($className);
```

**Comment by Danack** [comment]
I think this should be out of scope for this plugin.

This plugin is for when the thing being made is of a single type, and can be reasoned about with absolute clarity. When the thing being made is a variable then unless the rest of the program can be understood by the plugin completely, then there will always be some vagueness.

**Comment by alecsammon** [comment]
Sorry - I hadn't thought through all the implications of this request. Agreed!
