### ISSUE TITLE
Plugin broken in the newest PHPStorm EAP 141.1619

### ISSUE THREAD

**Issue by bashofmann** [pbyrne84/DynamicReturnTypePlugin#45]
The plugin does not work anymore in the newest PHPStorm EAP 141.1619

Looking at the release notes https://confluence.jetbrains.com/display/PhpStorm/PhpStorm+EAP+141.1619+Release+Notes it may be connected to one of these changes:

https://youtrack.jetbrains.com/issue/WI-23395
https://youtrack.jetbrains.com/issue/WI-18075
https://youtrack.jetbrains.com/issue/WI-17116

**Comment by pbyrne84** [comment]
I had a feeling the following might cause issues.
https://youtrack.jetbrains.com/issue/WI-18075
https://youtrack.jetbrains.com/issue/WI-17116

I'll see the damage.

**Comment by pbyrne84** [comment]
I take it you use ::class? The internal representation of it changed a bit breaking resolution.

If that is all I'll have a fix uploaded in an hour or so. Lots of stuff was deprecated in Kotlin which the majority of the plugin was written in so I had to spend a day the other day cleaning it up.

**Comment by pbyrne84** [comment]
New upload with fixes for ::class... Let me know if that fixes your issues.

Thanks :)

**Comment by bashofmann** [comment]
Works, thanks for the fast fix :)
