### ISSUE TITLE
Allow ::class constant be used as parameter.

### ISSUE THREAD

**Issue by Strate** [pbyrne84/DynamicReturnTypePlugin#49]
Seems that ::class constant is not working for completion.

**Comment by pbyrne84** [comment]
Could you give me the  phpstorm/php plugin build version? The internal api
can change slightly in releases and 9.5 EAP is doing the rounds so I have
to watch out for stuff.

Thanks

**Comment by Strate** [comment]
I am using 141.2462 (9.0.2) now.

**Comment by pbyrne84** [comment]
Can I have a bit more of an example as this seems to be an uncovered edge case/change.  

Thanks

**Comment by Strate** [comment]
I created repository:
https://github.com/Strate/dynamicReturnTypePluginTest/tree/master

**Comment by pbyrne84** [comment]
Aaah, okay it is the array access bit.

Cheers

**Comment by pbyrne84** [comment]
I started doing it but it turned into a rabbit hole so I released 50 on its own. I will get back to your 49 tomorrow

**Comment by pbyrne84** [comment]
2.0.5 which I just uploaded should fix this issue.

**Comment by Strate** [comment]
Seems it fixed! Thank you!
