### ISSUE TITLE
Not resolving const FOO = Bar::class

### ISSUE THREAD

**Issue by norrs** [pbyrne84/DynamicReturnTypePlugin#50]
git clone https://github.com/norrs/dynamic_issue

see Fail.php, why doesn't $thisShouldBeBar resolve?

**Comment by pbyrne84** [comment]
Cool, thanks for the example I could checkout it is a big big help as the big test environment is great for checking stability as new versions of intellij etc come out but so big now not so fun trying to figure out these little edge cases as there is not real documentation on this stuff. I never envisioned class constants assigned to class constants which would then alias to ::class somewhere.

Anyway it took me a little while but I have found it is doable.

Cheers

**Comment by norrs** [comment]
Do you have an estimated time frame for when this could be fixed? Would greatly help phpstorm's introspection in our project. Can I personally sponsor you somehow via paypal etc? 

Else thanks for your work and great plugin! :-)

**Comment by pbyrne84** [comment]
Well I have fixed your edge case but now I need to re-add my edge cases and
try to make it recursive so it can go down more than 1 level. So you are
looking at tonight/monday night

**Comment by pbyrne84** [comment]
Always those cases are resolved but I have to wait to monday. In theory it will keep on trucking until it finds something it can make sense of.

**Comment by norrs** [comment]
Thanks! Our use case is that we have a configuration file and some reflection "magic" to initialize defined service interfaces defined in a services interface with constants. 
( in case you were curious what my use case was )

**Comment by pbyrne84** [comment]
Should be done

**Comment by norrs** [comment]
@pbyrne84 : Thanks, I'll give it a spin at work tomorrow and let you know :+1:

**Comment by norrs** [comment]
Confirmed it to be working! Thanks! :-)

**Comment by pbyrne84** [comment]
Nice...
