### ISSUE TITLE
Not working with constants

### ISSUE THREAD

**Issue by tobeorla** [pbyrne84/DynamicReturnTypePlugin#56]
First: ¡Thanks for creating this plugin!

Having:
DummyClass.php
```php
<?php

namespace Example;

class DummyClass {

    const MESSAGE = "hi";

    public static function say ($message) {
        echo $message;
    }
}
```

dynamicReturnTypeMeta.json
```js
{
  "methodCalls": [
    {
      "class": "\\Example\\DummyClass",
      "method": "say",
      "position" : 0,
      "fileReturnTypeReplacementCall": ["test.js", "replaceTag"]
    }
  ]
}
```

test.js
```js
//noinspection JSUnusedGlobalSymbols
/**
 * @type{com.ptby.dynamicreturntypeplugin.scripting.api.ExecutingScriptApi}
 */
var api;

//noinspection JSUnusedGlobalSymbols
function replaceTag (namespace, className) {
    return 'Laravel\\Service\\Sender';
}
```

If i send an string var, it wil work:
```php
<?php

namespace House;

use \Example\DummyClass;

DummyClass::say("this works")->[Sender methods suggest appears]
```

If i send a constant, it won't:
```php
<?php

namespace House;

use \Example\DummyClass;

DummyClass::say(DummyClass::MESSAGE)->[no suggestions]
```

This will also work:
```php
<?php

namespace House;

use \Example\DummyClass;

DummyClass::say(DummyClass::MESSAGE . "")->[Sender methods suggest appears]
```

**Comment by pbyrne84** [comment]
Okay, thanks for the good  example. I'll have a look soon. I need to upgrade all my environment to idea 15 etc and deal with the kotlin deprecations.

**Comment by tobeorla** [comment]
¡¡Thanks!! And again, 
¡Thank you for creating this plugin!

**Comment by pbyrne84** [comment]
Okay there is a build here https://github.com/pbyrne84/DynamicReturnTypePlugin/tree/a39ee89e49a22636b5e91c2729e84969847d7e8c/deploy  that should fix it. Just replace the DynamicReturnTypePlugin folder on you machine with this ones contents. I'll do a release when I go back to work at the beginning of next year.

**Comment by tobeorla** [comment]
Now it works, thanks!!
Closing issue
