### ISSUE TITLE
Script engine calls issue with multiple files

### ISSUE THREAD

**Issue by mhujer** [pbyrne84/DynamicReturnTypePlugin#62]
In some cases, JavaScript callback is called with incorrect parameters. It seems that it depends on whether all the classes are in one file or in the multiple files.

I've created a demo which can be used to reproduce the issue:

https://github.com/pbyrne84/DynamicReturnTypePluginTestEnvironment/compare/master...mhujer:demo-multi?expand=1

When I try to use autocompletion for `$out->boo();` in `TestEnvironment/demo/demo.php`, it does not work because the JavaScript callback is called with `C\DataProvider.returnData`.

But when I copy the `DataProvider` class into `demo.php`, it starts working and `\FooX[]` is passed to JavaScript callback as expected.

(PHPStorm 2016.1, plugin 2.0.8.1)

**Comment by mhujer** [comment]
It seems that same issue happens for calls without JavaScript callback (type resolution does not work properly and incorrect types are passed if I switch it to callbacks).

**Comment by mhujer** [comment]
Ref: https://github.com/pbyrne84/DynamicReturnTypePluginTestEnvironment/pull/2

**Comment by pbyrne84** [comment]
Just a quick question did I fix everything for you? I think I have to
duplicate the stuff done down none script engine paths. Been pretty busy
and my brain has been wiped. Thanks
..

**Comment by pbyrne84** [comment]
Okay I made it parse down non script routes as I think that was the issue
